CREATE TABLE T_PAGAMENTO (
    ID BIGSERIAL NOT NULL,
    DATA_PAGAMENTO TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE T_USER ( 
    ID BIGSERIAL NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    GENERO BYTEA NOT NULL,
    ESTADO_CIVIL BYTEA NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DATA_REGISTRO TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE T_PRODUTO (
    ID BIGSERIAL NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE T_CAMPO (
    ID BIGSERIAL NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    OBRIGATORIO BOOLEAN NOT NULL,
    PRODUTO_ID_FK BIGINT,
    PRIMARY KEY(ID),
    FOREIGN KEY (PRODUTO_ID_FK) REFERENCES T_PRODUTO (ID)
);

CREATE TABLE T_ADESAO (
    ID BIGSERIAL NOT NULL,
    STATUS_ADESAO BYTEA NOT NULL,
    DATA_AQUISICAO TIMESTAMP,
    DIA_VENCIMENTO INT NOT NULL,
    NUMERO_PARCELAS INT NOT NULL,
    VALOR FLOAT NOT NULL,
    PRODUTO_ID_FK BIGINT,
    USER_ID_FK BIGINT ,
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUTO_ID_FK) REFERENCES T_PRODUTO (ID),
    FOREIGN KEY (USER_ID_FK) REFERENCES T_USER (ID)
);

CREATE TABLE T_RESPOSTA (
    ID BIGSERIAL NOT NULL,
    VALOR VARCHAR(255) NOT NULL,
    CAMPO_ID_FK BIGINT,
    ADESAO_RESPOSTA_ID_FK BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ADESAO_RESPOSTA_ID_FK) REFERENCES T_ADESAO (ID),
    FOREIGN KEY (CAMPO_ID_FK) REFERENCES T_CAMPO (ID)
);

CREATE TABLE T_COBRANCA (
    ID BIGSERIAL NOT NULL,
    DATA_COBRANCA TIMESTAMP NOT NULL,
    STATUS_COBRANCA INT NOT NULL,
    VALOR FLOAT NOT NULL,
    PAGAMENTO_ID_FK BIGINT,
    ADESAO_COBRANCA_ID_FK BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAGAMENTO_ID_FK) REFERENCES T_PAGAMENTO (ID),
    FOREIGN KEY (ADESAO_COBRANCA_ID_FK) REFERENCES T_ADESAO (ID)
);