CREATE TABLE T_PAGAMENTO (
    ID BIGSERIAL NOT NULL,
    DATA_PAGAMENTO TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE T_COBRANCA (
    ID BIGSERIAL NOT NULL,
    DATA_COBRANCA TIMESTAMP NOT NULL,
    STATUS_COBRANCA INT NOT NULL,
    VALOR FLOAT NOT NULL,
    PAGAMENTO_ID_FK BIGINT,
    ID_ADESAO_FK BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAGAMENTO_ID_FK) REFERENCES T_PAGAMENTO (ID)
);